Lesson#4:
Vasilevskiy-dmitriy/theme_for_NIX pull request #8
Opened 2021-12-18 04:40 UTC by Vasilevskiy-dmitriy

update functions
created structure for classes
added blocks ACF
created home page use ACF blocks
rewrote single post type use ACF blocks
ACF block slider
corrected code

2021-12-21 19:58 UTC, KirillGritcenko requested changes

2021-12-21 19:58 UTC, KirillGritcenko commented on template-parts/filter/movie-filter.php
> +            <option value="60" <?php if( ($_GET[ 'time' ]) == 60 ) { echo 'selected'; } ?> >До 60</option>
"До 60" "До 90" и т.д должны быть обернуты в языковую функцию.

2021-12-21 19:58 UTC, KirillGritcenko commented on template-parts/filter/movie-filter.php
> +            <option value="90" <?php if( ($_GET[ 'time' ]) == 90 ) { echo 'selected'; } ?> >До 90</option>
`if( ($_GET[ 'time' ]) == 90 ) { echo 'selected'; }` можно заменить функцией https://developer.wordpress.org/reference/functions/selected/
Делает тоже самое, но меньше строчек кода

2021-12-21 19:58 UTC, KirillGritcenko commented on template-parts/filter/movie-filter.php
>      function fun1() {
Очень плохая практика так называть функции. Не понятно что она делает. Функция должна коротко и точно отражать ее предназначение

2021-12-21 19:58 UTC, KirillGritcenko commented on template-parts/filter/latest-added-movies.php
> +    .row-title {
Стили перенеси в отдельный файл

2021-12-21 19:58 UTC, KirillGritcenko commented on template-parts/filter/movie-filter.php
> +            <option value="90" <?php if( ($_GET[ 'time' ]) == 90 ) { echo 'selected'; } ?> >До 90</option>
Этот момент проверить во всем коде, не только в этом конкретном темплейте

2021-12-21 19:58 UTC, KirillGritcenko commented on template-parts/ACF_block/slider.php
> +        <span class="visually-hidden">Previous</span>
Контролы тоже должны быть обернуты в языковые функции

2021-12-21 19:58 UTC, KirillGritcenko commented on template-parts/ACF_block/slider.php
> +        <?php for ( $i = 0; $i <= $quantity_img;  $i++  ): ?>
Тут можно спокойно обойтись циклом foreach ($image as $key => $value). Будет меньше кода, а делает тоже самое

2021-12-21 19:58 UTC, KirillGritcenko commented on template-parts/ACF_block/slider.php
> +        <div class="<?php if($i === 0){ echo 'carousel-item active'; } else { echo 'carousel-item'; }?>">
`<?php if($i === 0){ echo 'carousel-item active'; } else { echo 'carousel-item'; }?>`
Эту штуку можно здорово сократить через тернарный оператор. https://www.php.net/manual/en/language.operators.comparison.php#language.operators.comparison.ternary

2021-12-21 19:58 UTC, KirillGritcenko commented on template-parts/ACF_block/render_posts.php
> +                    <a href="<?php the_permalink(); ?>" class="stretched-link">Continue reading</a>
Обернуть текст в языковую функцию

2021-12-21 19:58 UTC, KirillGritcenko commented on template-parts/ACF_block/info_about_movie.php
> +            <img width="230px" src="<?php echo ( $image[ 'url' ] ); ?>">
Картинки в 99% случаев нужно выводить через функции WP: https://developer.wordpress.org/reference/functions/wp_get_attachment_image/

2021-12-21 19:58 UTC, KirillGritcenko commented on template-parts/ACF_block/improved_render_movies.php
> +    .b-example-divider {
Стили нужно вынести в отдельный файл

2021-12-21 19:58 UTC, KirillGritcenko commented on single-movie.php
> +<!--        <div class="col-md-8">-->
Закомментированный код не нужно хранить под гитом. Ты и так уже используешь гит, пред. версия файла хранится в нем и ты всегда можешь ее достать

2021-12-21 19:58 UTC, KirillGritcenko commented on classes/modules/custom_filter_CPT.php
> +class custom_filter_CPT{
Первые буквы класса по кодстайлу должны быть Заглавными. Так же посмотри название файла, оно не соответствует кодстайлу.

2021-12-21 19:58 UTC, KirillGritcenko commented on classes/modules/custom_CPT.php
> +class custom_CPT
Попробуй сделать этот класс по аналогии с блоками - чтоб сами настройки CPT у тебя хранились в конфиге, а регистрация шла через этот класс

2021-12-21 22:16 UTC, Vasilevskiy-dmitriy commented on template-parts/filter/movie-filter.php
> +            <option value="60" <?php if( ($_GET[ 'time' ]) == 60 ) { echo 'selected'; } ?> >До 60</option>
А если просто число, то нужно оборачивать или не имеет смысла т.к. числа на всех языка одинаковые ?

2021-12-26 10:25 UTC, KirillGritcenko requested changes

2021-12-26 10:25 UTC, KirillGritcenko commented on template-parts/ACF_block/improved_render_movies.php
> +    <?php include 'style_imp_rend_mov.css';?>
Вспомнил как это можно сделать лучше. В аргументах регистрации блока можно прописать путь к файлу стилей, и ACF сам его подключит когда будет нужно: https://www.advancedcustomfields.com/resources/acf_register_block_type/ Смотри параметр enqueue_style

2021-12-26 14:28 UTC, merged